-- SELECT
--   'categoryID' AS column_name,
--   COUNT(*) AS null_count
-- FROM NWTDATA.NWT.CATEGORY
-- WHERE categoryID LIKE '%NULL%'
-- UNION ALL
-- SELECT
--   'categoryName' AS column_name,
--   COUNT(*) AS null_count
-- FROM NWTDATA.NWT.CATEGORY
-- WHERE categoryName LIKE '%NULL%'
-- UNION ALL
-- SELECT
--   'description' AS column_name,
--   COUNT(*) AS null_count
-- FROM NWTDATA.NWT.CATEGORY
-- WHERE description LIKE '%NULL%'
-- UNION ALL
-- SELECT
--   'picture' AS column_name,
--   COUNT(*) AS null_count
-- FROM NWTDATA.NWT.CATEGORY
-- WHERE picture LIKE '%NULL%'
