SELECT
  'employeeID' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(employeeID) LIKE '%NULL%' OR employeeID IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'lastName' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(lastName) LIKE '%NULL%' OR lastName IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'firstName' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(firstName) LIKE '%NULL%' OR firstName IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'title' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(title) LIKE '%NULL%' OR title IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'titleOfCourtesy' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(titleOfCourtesy) LIKE '%NULL%' OR titleOfCourtesy IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'birthDate' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(birthDate) LIKE '%NULL%' OR birthDate IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'hireDate' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(hireDate) LIKE '%NULL%' OR hireDate IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'address' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(address) LIKE '%NULL%' OR address IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'city' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(city) LIKE '%NULL%' OR city IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'region' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(region) LIKE '%NULL%' OR region IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'postalCode' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(postalCode) LIKE '%NULL%' OR postalCode IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'country' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(country) LIKE '%NULL%' OR country IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'homePhone' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(homePhone) LIKE '%NULL%' OR homePhone IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'extension' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(extension) LIKE '%NULL%' OR extension IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'photo' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(photo) LIKE '%NULL%' OR photo IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'notes' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(notes) LIKE '%NULL%' OR notes IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'reportsTo' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(reportsTo) LIKE '%NULL%' OR reportsTo IS NULL
HAVING COUNT(*) > 0

UNION ALL

SELECT
  'photoPath' AS column_name,
  COUNT(*) AS null_count
FROM NWTDATA.NWT.INTERMEDIATE_EMPLOYEE
WHERE UPPER(photoPath) LIKE '%NULL%' OR photoPath IS NULL
HAVING COUNT(*) > 0

