USE SCHEMA NWT;
ALTER TABLE RAW_PRODUCT ADD COLUMN Unitcost DECIMAL(5,2);


-- UPDATE RAW_PRODUCT 
-- SET RAW_PRODUCT.UnitCost = pf.UnitCost
-- FROM RAW_PRODUCT AS p
-- INNER JOIN RAW_PRODUCT_FRESH AS pf
-- ON p.productID = pf.productID;
UPDATE RAW_PRODUCT p
INNER JOIN RAW_PRODUCT_FRESH pf ON p.productID = pf.productID
SET p.UnitCost = pf.UnitCost;
