name: Load Data using SnowSQL
# Pre-testing loading method - tried to run query directly in github actions and failed.
on:
  push:
    paths:
      - 'loaddatatext.txt'

jobs:
  load_data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Load Data to Snowflake Stage
      run: |
        DBT_USER: ${{ secrets.SNOWFLAKE_USER }}
        DBT_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        DBT_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        
        # GitHub raw data URL
        github_raw_url: 'https://raw.githubusercontent.com/just4jc/Northwind-Traders-Dataset/main/category.csv'
        
        # Snowflake PUT command to load data into stage
        snowsql -a $snowflake_account_url -u $snowflake_username -p $snowflake_password -d $snowflake_database -s $snowflake_schema \
          -q "PUT file:///$GITHUB_WORKSPACE/data.csv @$snowflake_stage auto_compress=true overwrite=true"

# Additional steps can be added for further workflow requirements

